# Generated by Django 2.0.3 on 2019-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0002_testresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
