# Generated by Django 2.2 on 2019-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_dutch',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
