# Generated by Django 2.2 on 2019-04-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0005_subject_name_dutch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('page_url', models.CharField(max_length=255)),
                ('engl', models.CharField(max_length=2000)),
                ('dutch', models.CharField(max_length=2000)),
            ],
        ),
    ]
