# Generated by Django 2.2 on 2019-04-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0006_translationstring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationString',
        ),
    ]
