# Generated by Django 2.2 on 2019-04-13 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0007_delete_translationstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='difficult_questions_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresults',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testresults',
            name='initial_question_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresults',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testresults',
            name='total_question_amount',
            field=models.IntegerField(default=0),
        ),
    ]
