# Generated by Django 2.2 on 2019-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0008_auto_20190413_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='grade',
            field=models.FloatField(),
        ),
    ]
