# Generated by Django 2.2 on 2019-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0009_auto_20190413_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresults',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
