# Generated by Django 2.2 on 2019-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0010_auto_20190413_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tts_support',
            field=models.BooleanField(default=False),
        ),
    ]
