# Generated by Django 2.2.5 on 2019-10-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0011_subject_tts_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='list',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='learnit.List'),
        ),
    ]
