# Generated by Django 2.2.5 on 2019-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0013_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='lists',
            field=models.ManyToManyField(to='learnit.List'),
        ),
    ]
