# Generated by Django 2.2.5 on 2019-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnit', '0014_folder_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_on',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
